DATASET:
  END_DATE: 20211110
  INDICATORS:
    MA:
      WIN: 245
  LOOKBACK_WIN: 49
  MODE: train
  PARALLEL_NUM: 12
  SAMPLE_RATE: 0.2
  SHOW_VOLUME: false
  START_DATE: 20211101
INFERENCE:
  END_DATE: 20230630
  FACTORS_SAVE_FILE: /path/to/factors/I49R50_OHLC/I49R50_OHLC_2101-2306_Ed_1_0_0.csv
  START_DATE: 20210101
MODEL: CNN49u
PATHS:
  COMMONCACHE_DIR: /path/to/commoncache
  IMAGE_DATA_DIR: /path/to/image/data
  PROJECT_DIR: /path/to/project/output
TRAIN:
  BATCH_SIZE: 256
  EARLY_STOP_EPOCH: 5
  EDITION: Edition_1_0_0
  END_DATE: 20201231
  LABEL: RET_LONG
  LEARNING_RATE: 0.05
  LOG_SAVE_FILE: /path/to/logs/I49R50_OHLC/I49R50_OHLC_1701-2012_Ed_1_0_0.csv
  LR_BASE_RATE: 0.001
  MODEL_SAVE_FILE: /path/to/models/I49R50_OHLC/I49R50_OHLC_1701-2012_Ed_1_0_0.tar
  NEPOCH: 20
  PREDICT_WIN: 50
  START_DATE: 20170101
  VALID_RATIO: 0.06
  WARMUP_EPOCH: 1
  WEIGHT_DECAY: 0.01
